#!/bin/sh
echo "自动生成可发布的源码包..."

echo "1、调用 automake 和 autoconf 等标准工具"
autoreconf --install
if test $? != 0 ; then
echo "缺少标准开发工具 automake autoconf，请先安装开发工具"
exit 1
fi

echo "2、调用 ./configure 脚本自动完成各项检查"
./configure
if test $? != 0 ; then
echo "缺少开发库，请参考 Install.html 文档安装所有开发工具"
exit 2
fi

echo "3、调用 make 工具生成 tar.gz 源代码压缩包"
make dist --quiet
ls *.tar.gz || ls *.tar.bz2
